-- CREATE THE TABLE EMPLOYEES --
CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR (50),
    LAST_NAME VARCHAR (50),
    DEPARTMENT VARCHAR (50)
);

-- INSERT THE DATA --
INSERT INTO EMPLOYEES VALUES (1, 'MANU', 'MNINJA', 'SALES');
INSERT INTO EMPLOYEES VALUES (2, 'RUTH', 'GITHU', 'MARKETING');
INSERT INTO EMPLOYEES VALUES (3, 'YVONNE', 'MATOLE', 'SALES');
INSERT INTO EMPLOYEES VALUES (4, 'BRIAN', 'YOBRA', 'PROGRAMMING');

-- SYNTAX --
-- Write an SQL query to retrieve the first and last names of employees --
-- who belong to either the 'Sales' or 'Marketing' department --
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
WHERE DEPARTMENT IN('SALES', 'MARKETING');