-- CREATE THE DATABASE RECRUITER --
CREATE DATABASE RECRUITER;

-- USE THE DATABASE RECRUITER --
USE RECRUITER;

-- CREATE THE TABLE CANDIDATES --
CREATE TABLE CANDIDATES(
	CANDIDATES_ID INT PRIMARY KEY,
    YEARS_EXPERIENCE INT,
    EDUCATION_LEVEL VARCHAR (30),
    CERTIFICATION VARCHAR (20)
    );
    
DROP TABLE CANDIDATES;

    -- INSERT THE DATA INTO THE TABLE --
    INSERT INTO CANDIDATES VALUES(6709, 8, 'MASTERS COMPUTER SCIENCE', 'JAVA PROGRAMMING');
    INSERT INTO CANDIDATES VALUES(8977, 3, 'DIPLOMA COMPUTER ENGINEERING', 'PYTHON PROGRAMMING');
    INSERT INTO CANDIDATES VALUES(9863, 9, 'BACHELORS COMPUTER ENGINEERING', 'JAVA PROGRAMMING');
    INSERT INTO CANDIDATES VALUES(7653, 7, 'BACHELORS COMPUTER SCIENCE', 'PYTHON PROGRAMMING');
    
    -- SYNTAX --
    -- Have a master's degree in computer science AND --
    -- Have at least 5 years of experience in software development OR --
    -- Have a bachelor's degree in computer engineering AND --
    -- Have a certification in Java programming --
    -- Construct a SQL query to find these candidates --
    SELECT * FROM CANDIDATES
    WHERE (YEARS_EXPERIENCE >= 5 OR EDUCATION_LEVEL= 'BACHELORS COMPUTER ENGINEERING') AND CERTIFICATION = 'JAVA PROGRAMMING';
    
    